config/grub.d/emgd.cfg                              /etc/default/grub.d/

config/modprobe.d/blacklist-gma500.conf  /etc/modprobe.d/
config/modprobe.d/emgd.conf                   /etc/modprobe.d/
config/modprobe.d/emgdbl.conf                /etc/modprobe.d/

config/xorg.conf                                        /usr/share/emgd-driver/

config/initramfs/emgd                       /usr/share/initramfs-tools/modules.d/

config/modules-load.d/emgd.conf             /etc/modules-load.d/